### ISSUE TITLE
osm2pgsql crashes with "std::bad_alloc" inside libosmium

### ISSUE THREAD

**Issue by Zverik** [osmcode/libosmium#150] opened 2016-04-20 14:06 UTC
I'm trying to import a [700 MB pbf file](http://tile.osmz.ru/tileosmz.osm.pbf) to pgsql with osm2pgsql on a virtual machine with 1 GB of memory and 1 GB of swap. This fails, though it did work with much earlier versions of osm2pgsql, like 0.86.

What can I do to further debug this, or to get rid of the error?

Thanks.

```
zverik@tile:~$ gdb osm2pgsql                  
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
(gdb) set args  --slim -d gis -C 600 -S veloroad.style tileosmz.osm.pbf
(gdb) r
Starting program: /usr/local/bin/osm2pgsql --slim -d gis -C 600 -S veloroad.style tileosmz.osm.pbf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
osm2pgsql version 0.91.0-dev (64 bit id space)

Using built-in tag processing pipeline
Using projection SRS 3857 (Spherical Mercator)
Setting up table: planet_osm_point
Setting up table: planet_osm_line
Setting up table: planet_osm_polygon
Setting up table: planet_osm_roads
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=600MB, maxblocks=9600*65536, allocation method=11
Mid: pgsql, scale=100 cache=600
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels

Reading in file: tileosmz.osm.pbf
Using PBF parser.
[New Thread 0x7fffbfa1b700 (LWP 4772)]
[New Thread 0x7fffbf21a700 (LWP 4773)]
[New Thread 0x7fffbea19700 (LWP 4774)]
Processing: Node(18190k 129.0k/s) Way(0k 0.00k/s) Relation(0 0.00/s)[Thread 0x7fffbfa1b700 (LWP 4772) exited]
[New Thread 0x7fffbea19700 (LWP 4774)]
Processing: Node(18190k 129.0k/s) Way(0k 0.00k/s) Relation(0 0.00/s)[Thread 0x7fffbfa1b700 (LWP 4772) exited]
[Thread 0x7fffbf21a700 (LWP 4773) exited]
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Program received signal SIGABRT, Aborted.
0x00007ffff5f84cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) up
#1  0x00007ffff5f880d8 in __GI_abort () at abort.c:89
89      abort.c: No such file or directory.
#2  0x00007ffff688f535 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff688d6d6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff688d703 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff688d976 in __cxa_rethrow () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x000000000049735f in read (this=0x7fffffffdea0) at /home/zverik/src/osm2pgsql/contrib/libosmium/osmium/io/reader.hpp:341
341                         throw;
#7  osmium::io::InputIterator<osmium::io::Reader, osmium::memory::Item>::update_buffer (this=0x7fffffffdd40) at /home/zverik/src/osm2pgsql/contrib/libosmium/osmium/io/input_iterator.hpp:68
68                          m_buffer = std::make_shared<osmium::memory::Buffer>(std::move(m_source->read()));
#8  0x0000000000487f3b in operator++ (this=0x7fffffffdd40) at /home/zverik/src/osm2pgsql/contrib/libosmium/osmium/io/input_iterator.hpp:103
103                         update_buffer();
#9  apply<osmium::io::InputIterator<osmium::io::Reader>, parse_osmium_t> (end=..., it=...) at /home/zverik/src/osm2pgsql/contrib/libosmium/osmium/visitor.hpp:235
235             for (; it != end; ++it) {
#10 apply<osmium::io::Reader, parse_osmium_t> (c=...) at /home/zverik/src/osm2pgsql/contrib/libosmium/osmium/visitor.hpp:243
243             apply(std::begin(c), std::end(c), handlers...);
#11 parse_osmium_t::stream_file (this=this@entry=0x7fffffffe260, filename="tileosmz.osm.pbf", fmt="auto") at /home/zverik/src/osm2pgsql/parse-osmium.cpp:123
123         osmium::apply(reader, *this);
#12 0x00000000004612d3 in main (argc=<optimized out>, argv=<optimized out>) at /home/zverik/src/osm2pgsql/osm2pgsql.cpp:88
88                  parser.stream_file(filename, options.input_reader);
```

**Comment by joto** [comment] 2016-04-20 15:27
Probably duplicate of #140.

**Comment by Zverik** [comment] 2016-04-20 15:34
Even then, there should be a better way to report an out of memory error.

**Comment by joto** [comment] 2016-04-20 16:43
You have to open on issue on osm2pgsql then, they could catch that exception and do something with it.

**Closed** 2016-04-27 19:19 UTC
