### ISSUE TITLE
Ubsan issues for master based on LLVM 3.8

### ISSUE THREAD

**Issue by daniel-j-h** [osmcode/libosmium#148] opened 2016-04-05 22:30 UTC
@joto, I just ran the UB-sanitizer on libosmium master at 65df99b.

(Env: LLVM 3.8 release, clang with libc++, Boost 1.60 compiled against clang/libc++ via:
https://gist.github.com/daniel-j-h/8ee8c511f89ebe80821b)

Here are some critical ones:

1/

> Test command: /tmp/libosmium/build-ubsan/test/basic_test_types_from_string
> include/osmium/osm/entity_bits.hpp:98:67: runtime error: shift exponent -1 is negative

2/

> Test command: /tmp/libosmium/build-ubsan/test/geom_test_ogr
> test/t/geom/test_ogr.cpp:71:5: runtime error: member call on null pointer of type 'OGRPolygon'

3/

> Test command: /tmp/libosmium/build-ubsan/test/geom_test_wkb
> include/osmium/geom/wkb.hpp:145:21: runtime error: store to misaligned address 0x0000037c2205 for type 'uint32_t' (aka 'unsigned int'), which requires 4 byte alignment
> 0x0000037c2205: note: pointer points here
>  02 00 00 00 00 00 00  00 9a 99 99 99 99 99 09  40 cd cc cc cc cc cc 10  40 00 00 00 00 00 00 0c  40
>              ^

**Comment by joto** [comment] 2016-04-06 09:32
1/ Fixed in f1e457136350051e56a1321359158a519257a164.
2/ This should not be a null pointer. I added a check to the test and on my system the check doesn't fail. Might be some issue with different OGR versions?
3/ Unfortunately WKB uses misaligned integers. I'll have a look to see whether this can be fixed without introducing an extra copy.

**Comment by joto** [comment] 2016-04-08 12:43
I fixed the No 3, too. Am closing this now because I can't reproduce No 2 and don't think there is an issue there.

**Closed** 2016-04-08 12:42 UTC

**Comment by daniel-j-h** [comment] 2016-04-08 13:41
Thank you. Re No 3, I think type punning always needs to go through a memcpy, for strict-aliasing reasons on it's own (?)
