### ISSUE TITLE
CMake error about GEOS_LIBRARY and PROJ_LIBRARY set to NOTFOUND

### ISSUE THREAD

**Issue by dforsi** [osmcode/libosmium#139] opened 2015-12-03 18:49 UTC
After installing only important dependencies listed in https://github.com/osmcode/libosmium/wiki/Libosmium-dependencies I get a fatal error from cmake:
<pre>
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GEOS_LIBRARY
    linked by target "geom_test_geos" in directory /home/daniele/libosmium/test
    linked by target "geom_test_geos_wkb" in directory /home/daniele/libosmium/test
PROJ_LIBRARY
    linked by target "geom_test_projection" in directory /home/daniele/libosmium/test

-- Configuring incomplete, errors occurred!
</pre>

**Comment by joto** [comment] 2015-12-04 08:41
Those libraries are needed for the tests and/or examples. That's why they are required if you run cmake, because the cmake script is there to compile the tests and examples. If you only want to use libosmium, you don't have to run anything, just use the include files in your own program.

**Comment by dforsi** [comment] 2015-12-04 15:52
You are right that extra libraries are needed for tests and examples, but I can't even issue "make install" if cmake fails to do the configuration and make install also builds tests and examples.

With the attached patch to [treat undefined variables as boolean FALSE](https://github.com/osmcode/libosmium/files/52191/0001-Fix-disabling-tests-when-needed-libraries-are-not-fo.txt) the configuration phase succeeds, but then I see this link-time failure which seems unrelated to me:
<pre>
Linking CXX executable osmium_convert
CMakeFiles/osmium_convert.dir/osmium_convert.cpp.o: In function `std::string::begin()':
/usr/include//c++/4.8/bits/stl_iterator.h:787: undefined reference to `protozero::pbf_writer::reserve_bytes'
/usr/include//c++/4.8/bits/stl_iterator.h:779: undefined reference to `protozero::pbf_writer::reserve_bytes'
</pre>

**Comment by joto** [comment] 2015-12-04 16:01
Hm. Good point. I have to think about that.

Protozero isn't installed by default. Details here: https://github.com/osmcode/libosmium/wiki/Libosmium-dependencies#protozero-since-version-230

**Comment by dforsi** [comment] 2015-12-04 23:59
I can't install the copy of protozero provided with libosmium if I get the fatal error as in my first comment, but since I was compiling the examples, the compiler should use the internal copy anyway. However that error seems to be about the visibility of protozero::pbf_writer::reserve_bytes not about the availabilty of the includes, so it's a different issue.

**Comment by joto** [comment] 2016-07-20 12:29
@dforsi Can you verify that you can install now without all the dependencies?

Your protozero problems are unrelated, but should also be fixed now with newest protozero (not in libosmium included yet, please get it from https://github.com/mapbox/protozero). If the problem is still there, please open a new issue for that, so we don't get the two problems confused.

**Closed** 2016-07-27 08:10 UTC

**Comment by dforsi** [comment] 2016-08-07 15:09
Yes, I verified that I can install libosmium without all the dependencies (I only installed the "important dependencies" plus libboost-dev on a clean Debian 8.5)
